config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root to: 'tasks#index'

	resources :tasks

	resource :profile, only: [:show, :edit, :update]

	resources :cards do
		resources :comments, only: [:new, :create]
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  limit_date :date             not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_cards_on_user_id  (user_id)
#
class Card < ApplicationRecord
	validates :name, presence: true
	validates :content, presence: true
	validates :content, uniqueness: true
	validates :limit_date, presence: true
	has_one_attached :eyecatch
	has_many :comments, dependent: :destroy

	belongs_to :user

	def author_name
		user.display_name
	end

	def comment_count
		comments.count
	end


	def has_commented?(current_user)
		comments.where(user_id: current_user.id).exists?
	end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  card_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_comments_on_card_id  (card_id)
#  index_comments_on_user_id  (user_id)
#
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :card
	validates :content, presence: true
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id         :bigint           not null, primary key
#  nickname   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
	belongs_to :user
	has_one_attached :avatar
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_tasks_on_user_id  (user_id)
#
class Task < ApplicationRecord
	validates :name, presence: true
	validates :content, presence: true
	validates :content, uniqueness: true

	belongs_to :user

	def author_name
		user.display_name
	end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	devise :database_authenticatable, :registerable,
				:recoverable, :rememberable, :validatable

	has_many :tasks, dependent: :destroy
	has_many :cards, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :comment_cards, through: :comments, source: :card
	has_one :profile, dependent: :destroy

	def has_written?(task)
		tasks.exists?(id: task.id)
	end

	def has_described?(card)
		cards.exists?(id: card.id)
	end

	def display_name
		profile&.nickname || self.email.split('@').first
	end

	def prepare_profile
		profile || build_profile
	end

	def avatar_image
		if profile&.avatar&.attached?
			profile.avatar
		else
			'default-avatar.png'
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_action :set_card, only: [:show]
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@cards = Card.all
		@comments = Comment.all
	end

	def show
		@comments = @card.comments
	end

	def new
		@card = current_user.cards.build
	end

	def create
		@card = current_user.cards.build(card_params)
		if @card.save
			redirect_to card_path(@card), notice: 'Saved in.'
		else
			flash.now[:error] = 'Failed to save.'
			render :new
		end
	end

	def edit
		@card = current_user.cards.find(params[:id])
	end

	def update
		@card = current_user.cards.find(params[:id])
		if @card.update(card_params)
			redirect_to card_path(@card), notice: 'I was able to change it.'
		else
			flash.now[:error] = 'Could not change.'
			render :edit
		end
	end

	def destroy
		card = current_user.cards.find(params[:id])
		card.destroy!
		redirect_to cards_path, notice: 'Successfully deleted.'
	end

	private
	def card_params
		params.require(:card).permit(:name, :content, :limit_date, :eyecatch)
	end

	def set_card
		@card = Card.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def new
		card = Card.find(params[:card_id])
		@comment = card.comments.build
	end

	def create
		card = Card.find(params[:card_id])
		@comment = card.comments.build(comment_params)
		if @comment.save
			redirect_to card_path(card), notice: 'Add a comment'
		else
			flash.now[:error] = 'Could not update.'
			render :new
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:content).merge(user_id: current_user.id)
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def show
		@profile = current_user.profile
	end

	def edit
		@profile = current_user.prepare_profile
	end

	def update
		@profile = current_user.prepare_profile
		@profile.assign_attributes(profile_params)
		if @profile.save
			redirect_to profile_path, notice: 'Profile updated'
		else
			flash.now[:error] = 'Could not update.'
			render :edit
		end
	end

	private
	def profile_params
		params.require(:profile).permit(:nickname, :avatar)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :set_task, only: [:show]
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def index
		@tasks = Task.all
	end

	def show
	end

	def new
		@task = current_user.tasks.build
	end

	def create
		@task = current_user.tasks.build(task_params)
		if @task.save
			redirect_to task_path(@task), notice: 'Saved in.'
		else
			flash.now[:error] = 'Failed to save.'
			render :new
		end
	end

	def edit
		@task = current_user.tasks.find(params[:id])
	end

	def update
		@task = current_user.tasks.find(params[:id])
		if @task.update(task_params)
			redirect_to task_path(@task), notice: 'I was able to change it.'
		else
			flash.now[:error] = 'Could not change.'
			render :edit
		end
	end

	def destroy
		task = current_user.tasks.find(params[:id])
		task.destroy!
		redirect_to root_path, notice: 'Successfully deleted.'
	end

	private
	def task_params
		params.require(:task).permit(:name, :content)
	end

	def set_task
		@task = Task.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.haml
.container
  %h2 New Card
  %ul
    - card.errors.full_messages.each do |message|
      %li= message
  = form_with(model: card, local: true) do |f|
    %div
      = f.label :eyecatch, 'eyecatch'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    %div
      = f.label :limit_date, 'limit_date'
    %div
      = f.date_field :limit_date
    = f.submit 'Submit', class: 'btn-primary'

app/views/cards/edit.html.haml
= render 'form', card: @card

app/views/cards/index.html.haml
.container
  %h2 Brackets
  - @cards.each do |card|
    = render 'commons/card', card: card
  = link_to new_card_path do
    .card.add
      .card_content
        .add_new + Add new card

app/views/cards/new.html.haml
= render 'form', card: @card

app/views/cards/show.html.haml
.container
  .card_title.show
    = @card.name
    - if user_signed_in? && current_user.has_described?(@card)
      .card_detail_actions.show
        .dropdown
          = image_tag 'Combined Shape.svg', class: 'dropbtn'
          .dropdown-content.mini
            = link_to 'Edit', edit_card_path(@card)
            = link_to 'Delete', card_path(@card), data: { method: 'delete', confirm: 'Are you sure you want me to delete it?'}
    -if @card.eyecatch.attached?
      .card_image.show
        = image_tag @card.eyecatch
  .card
    .card_content
      .card_text.show
        = @card.content
      .card_limit
        = @card.limit_date
  .card.comment
    %h2 Comment
    - @comments.each do |comment|
      .card_detail
        = image_tag comment.user.avatar_image
        %p= comment.content
  = link_to new_card_comment_path(@card) do
    .card.add.comment
      .card_content
        .add_new + Add new comment

app/views/comments/new.html.haml
.container
	%h2 New Comment
	%ul
		- @comment.errors.full_messages.each do |message|
			%li= message
	= form_with(model: @comment, url: card_comments_path(@comment.card), local: true) do |f|
		%div
			= f.text_area :content
		= f.submit 'Submit', class: 'btn-primary'

app/views/commons/_card.html.haml
= link_to card_path(card) do
  .card
    - if card.eyecatch.attached?
      .card_image
        = image_tag card.eyecatch
    .card_content
      .card_title.index
        = card.name
      .card_text
        = card.content
      .card_limit
        = card.limit_date
      .card_detail.card_index
        = image_tag card.user.avatar_image
        - if card.has_commented?(current_user)
          - @comments.each do |comment|
            = image_tag comment.user.avatar_image
        .card_count
          %span= card.comment_count
          = image_tag 'message-square-outline.svg'

app/views/commons/_task.html.haml
= link_to task_path(task) do
  .card
    .card_content
      .card_title
        = task.name
      .card_text
        = task.content
      .card_detail
        = image_tag task.user.avatar_image

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Todo2App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      %p.header_pageTitle
        = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'profile', profile_path
            = link_to 'log out', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'log in', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/profiles/edit.html.haml
.container
	%ul
		- @profile.errors.full_messages.each do |message|
			%li= message

	= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
		%div
			= f.label :avatar, 'avatar'
		%div
			= f.file_field :avatar
		%div
			= f.label :nickname, 'ハンドルネーム'
		%div
			= f.text_field :nickname, class: 'text'

			= f.submit 'Submit', class: 'btn-primary'

app/views/profiles/show.html.haml
.container.profilePage
  .profilePage_user
    .profilePage_user_image
      = image_tag current_user.avatar_image
    .profilePage_user_basicInfo
      .profilePage_user_name
        .profilePage_user_displayName
          = current_user.display_name
        .profilePage_user_actionButton
          = link_to 'Edit', edit_profile_path

  - current_user.tasks.each do |task|
    = render 'commons/task', task: task

app/views/tasks/_form.html.haml
.container
  %h2 New Board
  %ul
    - task.errors.full_messages.each do |message|
      %li= message
  = form_with(model: task, local: true) do |f|
    %div
      = f.label :name, 'Name'
    %div
      = f.text_field :name, class: 'text'
    %div
      = f.label :content, 'Description'
    %div
      = f.text_area :content
    = f.submit 'Submit', class: 'btn-primary'

app/views/tasks/_task.html.haml
= link_to task_path(task) do
  .card
    .card_content
      .card_title
        = task.name
      .card_text
        = task.content
      .card_detail
        = image_tag 'Users.png'

app/views/tasks/edit.html.haml
= render 'form', task: @task

app/views/tasks/index.html.haml
.container
  %h2 All Board
  - @tasks.each do |task|
    = render 'commons/task', task: task
  = link_to new_task_path do
    .card.add
      .card_content
        .add_new + Add new borad

app/views/tasks/new.html.haml
= render 'form', task: @task

app/views/tasks/show.html.haml
.container
  %h2 All Board
  = link_to cards_path do
    .card
      - if user_signed_in? && current_user.has_written?(@task)
        .card_detail_actions
          .dropdown
            = image_tag 'Combined Shape.svg', class: 'dropbtn'
            .dropdown-content.mini
              = link_to 'Edit', edit_task_path(@task)
              = link_to 'Delete', task_path(@task), data: { method: 'delete', confirm: 'Are you sure you want me to delete it?'}
      .card_content
        .card_title
          = @task.name
        .card_text
          = @task.content
        .card_detail
          = image_tag @task.user.avatar_image
  = link_to new_task_path do
    .card.add
      .card_content
        .add_new + Add new borad